---
- name: Wordpress
  hosts: localhost
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: true

  tasks:
    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ som3_pa55_wo7d }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]
      ignore_errors: true

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mariadb-server }}"
        state: present
        login_user: root
        login_password: "{{ som3_pa55_wo7d }}"
      tags: [ mysql ]
      ignore_errors: true

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ Aida }}"
        password: "{{ Aidapa55wo7d }}"
        priv: "{{ mariadb-server }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ som3_pa55_wo7d }}"
      tags: [ mysql ]
      mysql_user:
      ignore_errors: true