---
- name: Wordpress
  hosts: localhost
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: true


    - name: Start Mariadb
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    systemd: 
      name: mariadb
      state: started
    ignore_errors: true

    - name: Enable mariadb
      shell: "systemctl enable mariadb"

    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ som3_pa55_wo7d }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ som3_pa55_wo7d }}"
      tags: [ mysql ]

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ som3_pa55_wo7d }}"
      tags: [ mysql ]  
    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ Aida }}"
        password: "{{ aida_s_pa55wo7d }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ som3_pa55_wo7d }}"
      tags: [ mysql ]    