---
- name: Create route53 entry
  hosts: 3.11.250.160
  tasks:
  - name: Route53 record
    route53:
      state: “present”
      zone: "aidadevops.com"
      record: “aidadevops.com
      type: NS
      ttl: 172800
      hosted_zone_id: "Z01304741G3I6QPTY8X8K" 
      ignore_errors: true
  - name: Hosts
    hosts: localhost
    tasks:
    - name: Change host 
      host: 3.11.250.160
      ignore_errors: true