---
- name: Create route53 entry
  hosts: 3.11.250.160
  tasks:
  - name: Route53 record
    route53:
      state: “present”
      zone: "aidadevops.com"
      record: “wordpress.aidadevops.com
      type: A
      ttl: 300
      ec2_access_key: "cat ~/.ssh/id_rsa.pub"
      become_method: sudo
      ignore_errors: true